nearcomponents/napps-nft-android-app

.idea/misc.xml, app/src/main/java/com/nearlabs/nftmarketplace/ui/create/dialog/CreateNFTDialog.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/main/MainFragment.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/sendNFTDialog/SendNFTBottomSheetDialog.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/sendNFTDialog/adapter/SendNFTAdapter.kt, app/src/main/res/drawable/ic_bg_create_nft_dialog.xml, app/src/main/res/drawable/ic_plus_create_nft.xml, app/src/main/res/drawable/ic_send_nft_arrow.xml, app/src/main/res/layout/dialog_create_nft.xml, app/src/main/res/layout/dialog_send_nft.xml, app/src/main/res/layout/item_layout_send_nft_cell.xml, app/src/main/res/navigation/nav_bottom_nav_screens.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
=> NFTANDROID-32-37

app/src/main/java/com/nearlabs/nftmarketplace/data/networks/NFTApi.kt
=> NFTANDROID-72

app/src/main/java/com/nearlabs/nftmarketplace/data/localcontact/ContactSource.kt, app/src/main/java/com/nearlabs/nftmarketplace/data/localcontact/LocalContact.kt, app/src/main/java/com/nearlabs/nftmarketplace/data/networks/ContactApi.kt, app/src/main/java/com/nearlabs/nftmarketplace/data/networks/response/DtoContact.kt, app/src/main/java/com/nearlabs/nftmarketplace/domain/model/Contact.kt, app/src/main/java/com/nearlabs/nftmarketplace/repository/Repository.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/auth/SignupFragment.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/gift/GiftFragment.kt, app/src/main/java/com/nearlabs/nftmarketplace/util/adapters/ContactListAdapter.kt, app/src/main/res/layout/fragment_gift_nft.xml, app/src/main/res/navigation/nav_auth.xml
- Fixed import contact 
- Fixed send NFT with contact ID
- Fixed first name and last name issue
=> NFTANDROID-77

app/src/main/java/com/nearlabs/nftmarketplace/data/networks/LoginApi.kt, app/src/main/java/com/nearlabs/nftmarketplace/data/networks/response/DtoVerifyLoginResponse.kt, app/src/main/java/com/nearlabs/nftmarketplace/repository/Repository.kt
Fixed bug where the token would not propogate/be saved correctly when logging in (as opposed to creating a user where it would be saved correctly). Had to add another response for verify login and then propogate that change through.
=> Nftadroid-79

app/src/main/res/layout/fragment_login.xml, app/src/main/res/layout/fragment_otp.xml, app/src/main/res/values/strings.xml
Replaced the word verification with authentication.
=> Nama 88 jonathan

.idea/deploymentTargetDropDown.xml, app/src/main/java/com/nearlabs/nftmarketplace/repository/Repository.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/auth/LoginFragment.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/auth/OTPFragment.kt, app/src/main/java/com/nearlabs/nftmarketplace/util/adapters/ContactListAdapter.kt, app/src/main/java/com/nearlabs/nftmarketplace/viewmodel/UserViewModel.kt, app/src/main/res/layout/fragment_gift_nft.xml
- Fixed import text issue on Gift page
- Fixed import contact and display phone number or email
- Fixed OTP type issue.
=> NAMA-94,95,96 Minor UI Fixes

app/src/main/AndroidManifest.xml
Locked orientation in the portrait mode also tested it on my Android device.
=> Locked orientation to portrait mode only for the app.

app/src/main/java/com/nearlabs/nftmarketplace/ui/MainActivity.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/auth/SignupFragment.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/base/activity/BaseActivity.kt, app/src/main/java/com/nearlabs/nftmarketplace/util/AlertDialogUtil.kt, app/src/main/res/layout/custom_progress_dialog_layout.xml
Added Alert dialog util
Added alert dialog custom layout
Added loader for signup action
=> Added base activity

app/src/main/java/com/nearlabs/nftmarketplace/repository/Repository.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/auth/LoginFragment.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/auth/SignupFragment.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/gift/GiftFragment.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/sendNFTDialog/SendNFTBottomSheetDialog.kt, app/src/main/java/com/nearlabs/nftmarketplace/util/adapters/ContactListAdapter.kt, app/src/main/java/com/nearlabs/nftmarketplace/viewmodel/ContactViewModel.kt, app/src/main/res/layout/fragment_gift_nft.xml, app/src/main/res/layout/item_contacts.xml
- fixed "+" to be included in phone number
- fixed import contact logic and flow
- fixed signup Fragment UI (buttons not showing at the bottom)
-...
=> Nama 112 116 + others

app/src/main/java/com/nearlabs/nftmarketplace/ui/setting/SettingFragment.kt
Fixed where it wouldn't eliminate the bottom nav bar when signing out.
=> NAMA-117 and NAMA-118

.idea/misc.xml, app/src/main/java/com/nearlabs/nftmarketplace/ui/create/CreateNftFragment.kt, app/src/main/res/layout/fragment_add.xml, app/src/main/res/layout/inc_nft_upload.xml, app/src/main/res/values/strings.xml
NAMA 94
NAMA 100
NAMA 103
NAMA 123
NAMA 129
NAMA 130
NAMA 131
=> minor-UI-fixes

app/src/main/java/com/nearlabs/nftmarketplace/ui/gift/GiftFragment.kt, app/src/main/res/layout/fragment_gift_nft.xml, app/src/main/res/values/styles.xml
Completely fixed and tested (developer) the search view issues as mentioned in the NAMA 115 details.
=> NAMA 115 fixed

.idea/misc.xml, app/src/main/java/com/nearlabs/nftmarketplace/ui/auth/LoginFragment.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/auth/SignupFragment.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/base/adapter/BaseAdapter.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/base/adapter/BaseSelectionAdapter.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/gift/GiftFragment.kt, app/src/main/java/com/nearlabs/nftmarketplace/util/adapters/ContactListAdapter.kt, app/src/main/java/com/nearlabs/nftmarketplace/viewmodel/ContactViewModel.kt, app/src/main/res/layout/fragment_gift_nft.xml, app/src/main/res/layout/fragment_login.xml, app/src/main/res/layout/fragment_setting.xml, app/src/main/res/layout/fragment_signup.xml, app/src/main/res/layout/item_contacts.xml, app/src/main/res/navigation/nav_auth.xml
- removed 2FA authentication section
- fixed core issues in BaseAdapter 
- fixed core issues in BaseSelection
- fixed core issues in searchView
- added logic for correct selection
- adjusted buttons height in signUp screen
- adjusted .near label to be fixed in end of corresponding fields
=> Nama 111 121

.idea/misc.xml, app/src/main/java/com/nearlabs/nftmarketplace/ui/create/CreateNftFragment.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/mynfts/MyNFTsFragment.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/sendNFTDialog/SelectPeopleBottomSheetDialog.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/setting/changewallet/ChangeNameBottomSheetDialog.kt, app/src/main/java/com/nearlabs/nftmarketplace/util/adapters/NFTPropertiesAdapter.kt, app/src/main/java/com/nearlabs/nftmarketplace/viewmodel/CreateNftViewModel.kt, app/src/main/res/layout/dialog_send_select_people_ntf.xml, app/src/main/res/layout/fragment_home.xml, app/src/main/res/layout/inc_nft_upload.xml, app/src/main/res/layout/list_item_properties.xml
- added multi properties supports for create NFT (adapter, UI change, view model change, etc.)
- fixed overlapping contacts with upper layout in select people bottom dialog
- adjusted name in "change name layout" to be set as text, not hint
=> Nama 102 & NAMA 104 & NAMA 107

app/src/main/java/com/nearlabs/nftmarketplace/ui/auth/LoginFragment.kt
fixed a bug with .near in the login.
=> Fixed for NAMA-132 and Bug

app/src/main/java/com/nearlabs/nftmarketplace/data/networks/Api.kt, app/src/main/java/com/nearlabs/nftmarketplace/data/networks/request/DtoUserRequest.kt, app/src/main/java/com/nearlabs/nftmarketplace/data/networks/response/DtoUserResponse.kt, app/src/main/java/com/nearlabs/nftmarketplace/repository/Repository.kt, app/src/main/java/com/nearlabs/nftmarketplace/repository/SettingsRepository.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/auth/LoginFragment.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/auth/OTPFragment.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/setting/SettingFragment.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/setting/SettingsViewModel.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/setting/changewallet/ChangeEmailBottomSheetDialog.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/setting/changewallet/ChangeNameBottomSheetDialog.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/setting/changewallet/ChangePhoneBottomSheetDialog.kt, app/src/main/java/com/nearlabs/nftmarketplace/util/Helpers.kt, app/src/main/java/com/nearlabs/nftmarketplace/viewmodel/UserViewModel.kt, app/src/main/res/navigation/nav_auth.xml, app/src/main/res/navigation/nav_setting.xml, app/src/main/res/values/strings.xml
Added in change email, change name, and change phone flows.
=> NAMA-122 and NAMA-146

.idea/misc.xml, app/src/main/java/com/nearlabs/nftmarketplace/ui/auth/LoginFragment.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/setting/SettingFragment.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/setting/SettingsViewModel.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/setting/changewallet/ChangeEmailBottomSheetDialog.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/setting/changewallet/ChangeNameBottomSheetDialog.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/setting/changewallet/ChangePhoneBottomSheetDialog.kt, app/src/main/res/layout/dialog_change_phone.xml, app/src/main/res/values/strings.xml
fixed change phone number to look like login (with picker for country) and also made it where the settings screen fields update when you update them.
-These are changes requested from QA
=> NAMA 122 and 146

app/src/main/java/com/nearlabs/nftmarketplace/ui/main/HomeFragment.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/mynfts/MyNFTsFragment.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/mynfts/adapter/MyNFTAdapter.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/sendNFTDialog/adapter/myNftsAdapter.kt
Added loading / replacement of placeholder images.
=> Nama 142 and NAMA 141 Loading images in MyNFTs

.idea/deploymentTargetDropDown.xml, .idea/misc.xml, app/src/main/java/com/nearlabs/nftmarketplace/ui/auth/SignupFragment.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/create/CreateNftFragment.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/create/NftMintedSheetDialog.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/gift/GiftFragment.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/sendNFTDialog/SendNFTBottomSheetDialog.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/sendNFTDialog/adapter/SendNFTAdapter.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/setting/changewallet/ChangePhoneBottomSheetDialog.kt, app/src/main/res/layout/fragment_gift_nft.xml, app/src/main/res/layout/fragment_nft_minted.xml, app/src/main/res/navigation/nav_main.xml, app/src/main/res/values/strings.xml
Nama 152, 153, 155, and NFT Mint Bug (Minted dialog not showing NFT picture and text.
=> Nama 152, 153, 155, and NFT Mint Bug

.idea/deploymentTargetDropDown.xml, .idea/misc.xml, app/src/main/java/com/nearlabs/nftmarketplace/ui/create/CreateNftFragment.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/gift/GiftFragment.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/sendNFTDialog/SendNFTBottomSheetDialog.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/sendNFTDialog/adapter/SendNFTAdapter.kt, app/src/main/java/com/nearlabs/nftmarketplace/ui/setting/changewallet/ChangePhoneBottomSheetDialog.kt, app/src/main/res/layout/fragment_gift_nft.xml, app/src/main/res/navigation/nav_main.xml
Added in fix for import flow as well as fix for NFT-Send image not loading.  MERGE NAMA 122 FIRST!  This includes those changes (for testing purposes).
=> Nama 137 and Small NFT Image Fix (MERGE NAMA-122 FIRST)
